package com.focusflow.core.domain.blocking.model

/**
 * Output decision generated by [com.focusflow.core.domain.blocking.engine.BlockingRulesEngine].
 */
sealed interface BlockingDecision {
    /** Application is allowed to be accessed. */
    data object Allow : BlockingDecision

    /**
     * Application must be blocked.
     *
     * @property reason The triggered blocking reason.
     * @property remainingSessionMs Time left in active focus session (if applicable).
     * @property message Calm message to display on the blocker overlay.
     */
    data class Block(
        val reason: BlockReason,
        val remainingSessionMs: Long? = null,
        val message: String = "This app is paused to help you stay focused.",
    ) : BlockingDecision

    /**
     * Non-blocking warning indicating the user is approaching their configured time limit.
     *
     * @property remainingLimitMs Milliseconds left before daily limit is exceeded.
     */
    data class WarnNearLimit(
        val remainingLimitMs: Long,
    ) : BlockingDecision
}
